services:
  app:
    tty: true
    stdin_open: true
    environment:
      - EDITOR=vi
    image: slidict/docker-rails:node20.10.0-npm10.2.5-ruby3.2.2-bundler-2.4.13
    build:
      context: .
      dockerfile: Dockerfile
    command: bash
    restart: always
